project:
  type: website
  output-dir: docs

website:
  title: "Laboratory of Functional Medicine!"
  page-footer: "© 2023 Vijaykumar Muley. All rights reserved."
  google-analytics:
    tracking-id: "G-B5FVC80FWJ"
    anonymize-ip: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - team.qmd
      - publications.qmd
      - resources.qmd
#      - positions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
