---
title: "Biographical Sketch"
---

I received my B.Sc. degree in Chemistry, Zoology, and Fishery Science in 2000 and my M.Sc. in Biotechnology in 2002 from Dr. Babasaheb Ambedkar Marathwada University in Aurangabad, India. In 2005, I completed my second M.Sc. degree in Bioinformatics at the University of Pune in Pune, India. In 2012, I obtained my Ph.D. degree in Bioinformatics from the Computational and Functional Genomics Laboratory at the Centre for Fingerprinting and DNA Diagnostics (CDFD) in Hyderabad, India, under the supervision of Dr. Akash Ranjan.

In April 2012, I joined the Indian Institute of Science Education and Research (IISER) in Pune, India as a postdoctoral scientist in Dr. Sanjeev Galande’s laboratory, where I worked on animal evolution, embryonic development, and epigenetic regulation. In October 2013, I moved to Jena, Germany as a staff scientist and worked on mathematical modeling of gene expression and regulation in breast cancers at the Leibniz Institute for Natural Product Research and Infection Biology, in the Network Modelling group headed by Professor Rainer Koenig. In February 2016, I was appointed as an assistant professor on a permanent basis at the Central University of Punjab in Bathinda, India in the Centre for Computational Sciences. However, I resigned from the position after a while and decided to work as a full-time researcher at University College Cork, National University of Ireland in Cork City, Ireland from September 2017. There, I worked on IFN-gamma and TNF-alpha signaling pathways involved in immune responses with Dr. Ken Nally. In April 2018, I was invited to join the Institute of Neurobiology at the National Autonomous University of Mexico (UNAM) in Queretaro, Mexico, as an assistant professor and senior scientist in the neural laboratory of neural development headed by Professor Alfredo Varela. At UNAM, I worked on various research projects in the field of neurobiology and studied the molecular basis of embryonic brain development, neuropsychiatric disorders, neurodegenerative and infectious diseases at the systems level. The National Council for Science and Technology (CONACYT), Government of Mexico, awarded me with a lifetime honorary distinction called Sistema Nacional de Investigadores nivel 1 (System of National Investigator level 1) and fellowship for three subsequent years. I left UNAM in November 2022 to take a break until July 2023. Currently, I am a visiting assistant professor in the School of Technology at Swami Ramanand Teerth Marathwada University (SRTMU) in Nanded, India.

I have published several research papers, book chapters, and a book in prestigious journals from Nature, Oxford, Elsevier, Springer, BioMedCentral, PLoS, and Frontiers publication houses. Currently, I have contracts to write and edit two books. I am also an editorial board member of Frontiers and Dove Medical Press journals and review research manuscripts for over 30 journals. I have received several national and international fellowships by competition, including UGC-NET, DBT-JRF, and UGC-JRF from the Indian government, travel fellowships from the European Science Foundation, and the International Society for Computational Biologists.