---
title: "Publications"
---

## Journal articles 



**Muley VY\***, Delahaye-Duriez Andree\* (2025): *Transcriptional coordination between intergenic RNA polymerase II-bound regions and nearby genes reveals functional specialization and disease association in peripheral blood*, Computational and Structural Biotechnology Journal, 2025 Nov 26:27(1):5523-5536

<a href="https://doi.org/10.1016/j.csbj.2025.11.060" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Jamdhade AR, Jadhav BR, **Muley VY**, Hivrale VK\* (2025): *Exploring the Biochemical Profile of Pheretima posthuma Intestinal Proteases: Unlocking Industrial and Biotechnological Opportunities*, Industrial Biotechnology, 2025 Apr 7 

<a href="https://doi.org/10.1089/ind.2025.0001" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Singh MS, Pyati A,  Rubi RD, Subramanian R, **Muley VY**, Ahmed A, Yellaboina S\*. (2024): *Systems-wide view of host-pathogen interactions across COVID-19 severities using integrated omics analysis*, iScience, 2024 Mar 15;27(3):109087

<a href="https://pubmed.ncbi.nlm.nih.gov/38384846" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1016/j.isci.2024.109087" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Rakshit S, More A, Gaikwad S, Gade A, Seniya C, **Muley VY**, Mukherjee A\*, Kamble K\*. (2024): *Role of Diosgenin in suppression of HIV-1 replication: An in vitro preclinical study*, Heliyon, 2024 Jan 12;10(2):e24350

<a href="https://pubmed.ncbi.nlm.nih.gov/38288021" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1016/j.heliyon.2024.e24350" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


**Muley VY**. (2023): *Editorial: Gene expression: epigenetic and transcriptional regulation in neurodegenerative diseases and ageing*, Front Neurosci. 2023 Dec 12;17:1342890.

<a href="https://pubmed.ncbi.nlm.nih.gov/38161795" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.3389/fnins.2023.1342890" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

Robles-Rodríguez C, **Muley VY**, González-Dávalos LM, Shimada A, Varela-Echavarría A, Mora O\*. (2023): *Microbial colonization dynamics of the postnatal digestive tract of Bos indicus calves*, Animal Science Journal. 2023 Sept 5;94(1):e13872

<a href="https://pubmed.ncbi.nlm.nih.gov/37666790" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1111/asj.13872" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


**Muley VY\***, König R. (2022): *Human transcriptional gene regulatory network compiled from 14 data resources*, Biochimie, 2022 Feb 1;193:115-125

<a href="https://pubmed.ncbi.nlm.nih.gov/34740743/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1016/j.biochi.2021.10.016" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Aviña-Padilla K, Ramírez-Rafael JA, Herrera-Oropeza GE, **Muley VY**, Valdivia DI, Díaz-Valenzuela E, García-García A, Varela-Echavarría A, Hernández-Rosales M. (2021): *Evolutionary Perspective and Expression Analysis of Intronless Genes Highlight the Conservation of Their Regulatory Role*, Frontiers in Genetics, 2021 Jul 9;12:654256

<a href="https://pubmed.ncbi.nlm.nih.gov/34306008/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.3389/fgene.2021.654256" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


**Muley VY\***, López-Victorio CJ, Ayala-Sumuano JT, González-Gallardo A, González-Santos L, Lozano-Flores C, Wray G, Hernández-Rosales M, Varela-Echavarría A. (2020): *Conserved and divergent expression dynamics during early patterning of the telencephalon in mouse and chick embryos*, Progress in Neurobiology, 2020 Mar 1;186:101735

<a href="https://pubmed.ncbi.nlm.nih.gov/31846713/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1016/j.pneurobio.2019.101735" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


**Muley VY\***, Akhter Y, Galande S. (2019): *PDZ Domains Across the Microbial World: Molecular Link to the Proteases, Stress Response, and Protein Synthesis*, Genome Biology and Evolution, 2019 Mar 1;11(3):644-659

<a href="https://pubmed.ncbi.nlm.nih.gov/30698789/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1093/gbe/evz023" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Jangid RK, Kelkar A, **Muley VY**, Galande S. (2018): *Bidirectional promoters exhibit characteristic chromatin modification signature associated with transcription elongation in both sense and antisense directions*, BMC Genomics, 2018 May 2;19(1):313

<a href="https://pubmed.ncbi.nlm.nih.gov/29716520/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1186/s12864-018-4697-7" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


VenkatRao V, Kumar SK, Sridevi P, **Muley VY**, Chaitanya RK. (2017): *Cloning, characterization and transmission blocking potential of midgut carboxypeptidase A in Anopheles stephensi*, Acta Tropica, 2017 Apr;168:21-28

<a href="https://pubmed.ncbi.nlm.nih.gov/28087198/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1016/j.actatropica.2016.12.035" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

Haldar KK, **Muley VY**, Datar S, Patra A. (2017): *Structural and electronic investigation of metal-semiconductor hybrid tetrapod hetero-structures*, Gold Bulletin, 2017 Mar 9;50:105--110

<a href="https://doi.org/10.1007/s13404-017-0198-8" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Salah FS, Ebbinghaus M, **Muley VY**, Zhou Z, Al-Saadi KR, Pacyna-Gengelbach M, O'Sullivan GA, Betz H, König R, Wang ZQ, Bräuer R, Petersen I. (2016): *Tumor suppression in mice lacking GABARAP, an Atg8/LC3 family member implicated in autophagy, is associated with alterations in cytokine secretion and cell death*, Cell Death & Disease, 2016 Apr 28;7(4):e2205

<a href="https://pubmed.ncbi.nlm.nih.gov/27124579/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1038/cddis.2016.93" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


Karmodiya K, Anamika K, **Muley VY**, Pradhan SJ, Bhide Y, Galande S. (2014): *Camello, a novel family of Histone Acetyltransferases that acetylate histone H4 and is essential for zebrafish development*, Scientific Reports, 2014 Aug 15;4:6076

<a href="https://pubmed.ncbi.nlm.nih.gov/25123547/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1038/srep06076" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


**Muley VY**, Ranjan A. (2013): *Evaluation of physical and functional protein-protein interaction prediction methods for detecting biological pathways*, PLOS One, 2013 Jan 17;8(1):e54325

<a href="https://pubmed.ncbi.nlm.nih.gov/23349851/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1371/journal.pone.0054325" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


**Muley VY**, Ranjan A. (2012): *Effect of reference genome selection on the performance of computational methods for genome-wide protein-protein interaction prediction*, PLOS One, 2012 Jul 26;7(7):e42057

<a href="https://pubmed.ncbi.nlm.nih.gov/22844541/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1371/journal.pone.0042057" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

Kamble KD, Bidwe PR, **Muley VY**, Kamble LH, Bhadange DG, Musaddiq M. (2012): *Characterization of L-asparaginase producing bacteria from water, farm and saline soil*, Bioscience discovery, 2012 Jan 1;3 (1), 116-119

<a href="https://jbsd.in/Vol%203%20No1/KDKamble116-119.pdf" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

Kamble KD, More A, **Muley VY**. (2012): *Effect of incubation on DNase production by a moderate thermophilic bacterium screened from arid land*, Journal of Pure and Applied Microbiology, 2012 Mar 31;6(1):265-269

<a href="https://microbiologyjournal.org/effect-of-incubation-on-dnase-production-by-a-moderate-thermophilic-bacterium-screened-from-arid-land/" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


## Books


**Muley, VY** (Ed.). (2025): *Computational virology*, Methods in Molecular Biology, 2025 May, Humana press, Springer Nature, New York, NY (ISBN 978-1-0716-4545-1)

<a href="https://link.springer.com/book/9781071645451" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>


**Muley VY**, Acharya V. (2012): *Genome-wide prediction and analysis of protein-protein functional linkages in bacteria*, SpringerBriefs in Systems Biology, 2012 Jul 28:Volume 2, Springer Nature (ISBN 978-1-4614-4705-4)

<a href="https://doi.org/10.1007/978-1-4614-4705-4" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

## Book chapters

### PubMed indexed protocols



**Muley VY\***. (2025): *Host Transcriptional Responses to Viral Infections: RNA-Seq Analysis with Rsubread, HISAT2, and STAR with Public RNA-Seq Data*, In: Muley, V.Y. (eds) Computational Virology. Methods in Molecular Biology, 2025;2927:23-50

<a href="https://pubmed.ncbi.nlm.nih.gov/40455150" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-4546-8_2" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

Le HTT, Ahamad I, **Muley VY\***. (2025): *Deciphering Host Differential Gene Expression in Viral Infections Through Public RNA-Seq Data from NCBI GEO*, In: Muley, V.Y. (eds) Computational Virology. Methods in Molecular Biology, 2025;2927:51-74

<a href="https://pubmed.ncbi.nlm.nih.gov/40455151" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-4546-8_3" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2025): *Exploring Virus Protein Domains: Detection and Evolutionary Insights*, In: Muley, V.Y. (eds) Computational Virology. Methods in Molecular Biology, 2025;2927:165-172

<a href="https://pubmed.ncbi.nlm.nih.gov/40455157" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-4546-8_9" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2025): *Functional Insights Through Gene Ontology, Disease Ontology, and KEGG Pathway Enrichment*, In: Muley, V.Y. (eds) Computational Virology. Methods in Molecular Biology, 2025;2927:75-98

<a href="https://pubmed.ncbi.nlm.nih.gov/40455152" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-4546-8_4" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2024): *Prediction and Analysis of Transcription Factor Binding Sites: Practical Examples and Case Studies Using R Programming*, In: Mandal, S. (eds) Reverse Engineering of Regulatory Networks. Methods in Molecular Biology, 2024;2719:199–225

<a href="https://pubmed.ncbi.nlm.nih.gov/37803120" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-3461-5_12" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2024): *Deep Learning for Predicting Gene Regulatory Networks: A Step-by-Step Protocol in R*, In: Mandal, S. (eds) Reverse Engineering of Regulatory Networks. Methods in Molecular Biology, 2024;2719:265–294

<a href="https://pubmed.ncbi.nlm.nih.gov/37803123" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-3461-5_15" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2023): *Centrality Analysis of Protein-Protein Interaction Networks Using R*, In: Mukhtar, S. (eds) Protein-Protein Interactions*, In: Mukhtar, S. (eds) Protein-Protein Interactions, Methods in Molecular Biology. 2023 Jul 15;2690:445-456 

<a href="https://pubmed.ncbi.nlm.nih.gov/37450165" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-3327-4_34" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2023): *Search, Retrieve, Visualize and Analyze Protein-Protein Interactions From Multiple Databases: A Guide to Experimental Biologists*, In: Mukhtar, S. (eds) Protein-Protein Interactions, Methods in Molecular Biology. 2023 Jul 15;2690:429-443  

<a href="https://pubmed.ncbi.nlm.nih.gov/37450164" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-3327-4_33" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2021): *Mathematical Linear Programming to Model MicroRNAs-Mediated Gene Regulation Using Gurobi Optimizer*, In: MUKHTAR, S. (eds) Modeling Transcriptional Regulation, Methods in Molecular Biology, 2021 Jul 13;2328:287-301

<a href="https://pubmed.ncbi.nlm.nih.gov/34251634/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-1534-8_19" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>

**Muley VY\***. (2021): *Mathematical Programming for Modeling Expression of a Gene Using Gurobi Optimizer to Identify Its Transcriptional Regulators*, In: MUKHTAR, S. (eds) Modeling Transcriptional Regulation, Methods in Molecular Biology, 2021 Jul 13;2328:99-113

<a href="https://pubmed.ncbi.nlm.nih.gov/34251621/" target="_blank" class="btn btn-primary btn-sm" role="button">PubMed</a>
<a href="https://doi.org/10.1007/978-1-0716-1534-8_6" target="_blank" class="btn btn-outline-primary btn-sm" role="button">Journal</a>


### Reference book chapters

Jamdhade AR, Hivrale VK, **Muley VY\***. (2024): *Darwin, Charles: On Evolutionary Foundation*. In: Shackelford, T. (eds) Encyclopedia of Religious Psychology and Behavior, 2024 July 23: Springer, Cham

<a href="https://doi.org/10.1007/978-3-031-38971-9_834-1" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

**Muley VY\***, Bojórquez SAF, Kamble KD. (2021): *Nervous System of Invertebrates*, Encyclopedia of Animal Cognition and Behavior, 2021 Mar 12: Springer, Cham

<a href="https://doi.org/10.1007/978-3-319-47829-6_1227-2" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

**Muley VY\***, Larriva-Sánchez F. (2019): *Nervous System, The*, Encyclopedia of Animal Cognition and Behavior, 2019 Aug 29: Springer, Cham

<a href="https://doi.org/10.1007/978-3-319-47829-6_589-1" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

**Muley VY\***, Gijón CET, García IM, Cueva LX. (2019): *Vertebrate Nervous System*, Encyclopedia of Animal Cognition and Behavior, 2019 Jun 26: Springer, Cham

<a href="https://doi.org/10.1007/978-3-319-47829-6_587-1" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

**Muley VY\***, Pathania A. (2018): *Gene Expression*, Encyclopedia of Animal Cognition and Behavior, 2018 Oct 20: Springer, Cham

<a href="https://doi.org/10.1007/978-3-319-47829-6_49-2" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

**Muley VY\***. (2017): *Bioinformatics*, Encyclopedia of Animal Cognition and Behavior, 2017 Sept 5: Springer, Cham

<a href="https://doi.org/10.1007/978-3-319-47829-6_41-1" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

Pathania A, **Muley VY\***. (2017): *Gene Expression Profiling*, Encyclopedia of Animal Cognition and Behavior, 2017 Aug 22: Springer, Cham

<a href="https://doi.org/10.1007/978-3-319-47829-6_9-1" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>

**Muley VY\***, Hahn A. (2016): *Protein-protein functional linkage predictions: bringing regulation to context*, Computational Biology & Bioinformatics: Gene Regulation, 2016 May 12, Taylor & Francis

<a href="https://www.taylorfrancis.com/chapters/mono/10.1201/b20026-13/protein-protein-functional-linkage-predictions-bringing-regulation-context-ka-chun-wong" target="_blank" class="btn btn-outline-success btn-sm" role="button">WebLink</a>


## In process/Preprints

**Muley VY\***, Singh A, Gruber K, Kamble KD, Varela-Echavarría A. (2023): *Potential functions of the amino-terminal cytoplasmic region of SARS-CoV-2 entry protein TMPRSS2 in virion assembly and early secretory pathway*, **In preparation**, A part of this work is available as a preprint at BioRxiv

<a href="https://doi.org/10.1101/2021.04.26.441280" target="_blank" class="btn btn-outline-default btn-sm" role="button">Preprint</a>



```{r, eval=FALSE, echo=FALSE}

## In preparation

  
**Muley VY\***. (2023): *Transcriptional Regulation of EOMES Gene Promoter*, **Submitted**

```